### ISSUE TITLE
minimum needed to complete RatePage

### ISSUE THREAD

**Issue by AimLow-SMM** [JosieBigler/movie-bros#11]
1. on login store display name. 
2. on `RatePage` load, grab any ratings that are already saved.
3. Display name added to message.

Display name and rated value are the two big values, all other values will only be used later on.

**Comment by JosieBigler** [comment]
-need an identity cookie accessable to client. This can also solve our "are we logged in" instead of saving a random variable in localstorage. This cookie will be removed on logout.  
-Also cleanup our Axios api calls in theclient. Its gross and I don't like it.

**Comment by JosieBigler** [comment]
LOL we have access to the User cookie in the Hub. Lets just make dat a THIC ass SEnd Message logic.

**Comment by JosieBigler** [comment]
Closing because we have other issues tracking the completion of rate page.
