### ISSUE TITLE
Weird red scribble

### ISSUE THREAD

**Issue by AimLow-SMM** [JosieBigler/movie-bros#14]
The code runs fine I've mostly been ignoring it. 
![image](https://github.com/JosieBigler/movie-bros/assets/78690774/5ff7385c-87de-4fa4-ad35-af50de38b879)
Conversion of type 'string' to type 'number' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.ts(2352)

**Comment by JosieBigler** [comment]
used`parseFloat(value)`  no longer there
