### ISSUE TITLE
Improve Rating UI

### ISSUE THREAD

**Issue by JosieBigler** [JosieBigler/movie-bros#18]
Two-ish improvements to the UI.  This issue is still fairly raw.  The main goal is to make it look less like a zug-zug backend with no frontend slapped a <input /><button /> 

1. The input rating is very gross. Something much cleaner. 

2. The displayed ratings is much better, but could probably take up more screen real-estate.  Maybe highlight certain values (lowest value is red, highest is green, your own value is X color)?   Maybe an animation when a new rating comes in.

**Comment by AimLow-SMM** [comment]
Local testing not posting movies. I'm unable to try things
