### ISSUE TITLE
Ratings - Front end 

### ISSUE THREAD

**Issue by JosieBigler** [JosieBigler/movie-bros#5]
front end 
1. we need a screen to rate a movie. 
2. We need to be able to send that rating to the backend. 
3. Need to redict to login if not logged in. 
4. Websockets for a rating update

**Comment by AimLow-SMM** [comment]
working on: Bros rating bubbles 
Even if no one has rated, there will be one bubble, the users own bubble, awaiting for them to input their rating.
The other bubbles will be dynamically generated based on those who have rated.

**Comment by AimLow-SMM** [comment]
Closing issue because parts are fulfilled and the rest should be put to narrower scoped issues. That are not generic and open-ended
